project:
  type: website
  output-dir: docs

website:
  navbar:
    background: "#1c3763"
    left:
      - href: index.qmd
        text: About
      - href: education.qmd
        text: Education
      - href: experience.qmd
        text: Experience
    right:
      - href: about.qmd
        text: "Blog"
    tools:
      - icon: github
        href: https://github.com/itsdebartha 
      - icon: linkedin
        href: https://www.linkedin.com/in/debartha-paul-90a296a9/

format:
  html:
    theme: 
      light: cosmo
      dark: superhero
    mainfont: Roboto
    css: styles.css
    toc: false



